# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Dockerfile for MCP Project Explorer
FROM node:lts-alpine AS builder
WORKDIR /app

# Install dependencies without running prepare scripts
COPY package.json package-lock.json* ./
RUN npm install --ignore-scripts

# Copy source and build
COPY tsconfig.json ./
COPY src ./src
RUN npm run build

# Final runtime image
FROM node:lts-alpine
WORKDIR /app
COPY --from=builder /app/build ./build
COPY --from=builder /app/node_modules ./node_modules

# Create non-root user
RUN addgroup -S appgroup && adduser -S appuser -G appgroup
USER appuser

ENTRYPOINT ["node", "build/index.js"]
